---
title: "Bayesian multilevel modelling and estimation of uncertainty in speaker variation"
author: "Stefano Coretta"
format: revealjs
---

```{r}
#| label: setup

library(tidyverse)
theme_set(theme_light())

library(coretta2019eng)
data("eng_durations")
library(brms)
library(tidybayes)

```

## Bayesian inference

$$
P(h \mid d) \propto P(h) \cdot P(d \mid h)
$$

where:

- $P(h)$ is the *prior probability* of $h$.
- $P(d \mid h)$ is the probability of $d$ given $h$ (aka *likelihood*).
- $P(h \mid d)$ is the *posterior probability* of $h$ given $d$.

## Bayesian updating

```{=html}
<iframe width="100%" height="500" src="https://nanx.shinyapps.io/conjugate-normal-umkv/"></iframe>
```

::: aside
App by [Nan Xiao](https://nanx.me), code on <https://github.com/nanxstats/conjugate-normal-umkv>
:::

## English voicing effect

```{r}
#| label: ve

eng_durations |> 
  ggplot(aes(vowel_ipa, v1_duration, colour = voicing)) +
  geom_jitter(alpha = 0.5, position = position_jitterdodge(jitter.width = 0.2)) +
  facet_grid(vars(num_syl)) +
  scale_color_brewer(type = "qual")

```

## Modelling

```{r}
#| label: ve-bm

ve_bm <- brm(
  v1_duration ~ voicing + (voicing | speaker),
  family = lognormal,
  data = eng_durations,
  cores = 4,
  seed = 2136,
  file = "data/cache/ve_bm"
)

```

```{r}
conditional_effects(ve_bm, "voicing")
```

```{r}
ve_speaker <- ve_bm |> 
  spread_draws(r_speaker[speaker,coef], b_voicingvoiced) |> 
  mutate(
    bs_voicing = b_voicingvoiced + r_speaker
  )
```

```{r}
ve_speaker |> 
  filter(coef == "Intercept") |> 
  ggplot(aes(r_speaker, reorder(speaker, r_speaker, median))) +
  geom_vline(xintercept = 0) +
  stat_halfeye()
```

```{r}
ve_speaker |> 
  filter(coef == "voicingvoiced") |> 
  ggplot(aes(r_speaker, reorder(speaker, r_speaker, median))) +
  geom_vline(xintercept = 0) +
  stat_halfeye()
```

```{r}
ve_speaker |> 
  filter(coef == "voicingvoiced") |> 
  ggplot(aes(bs_voicing, reorder(speaker, bs_voicing, median))) +
  geom_vline(xintercept = 0) +
  stat_halfeye()

ve_speaker |> 
  filter(coef == "voicingvoiced") |> 
  ggplot(aes(exp(bs_voicing), reorder(speaker, bs_voicing, median))) +
  geom_vline(xintercept = 1) +
  stat_halfeye()
```
